# Generated by Django 4.1.3 on 2025-10-05 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_stock', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('Yapı Kimyasalları', 'Yapı Kimyasalları'), ('Isı Yalıtım', 'Isı Yalıtım'), ('Yapıştırıcı', 'Yapıştırıcı'), ('Dekoratif Sıva', 'Dekoratif Sıva')], max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('current_qty', models.PositiveIntegerField(default=0)),
                ('pallet_size', models.PositiveIntegerField(default=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('IN', 'Giriş (+)'), ('OUT', 'Çıkış (-)')], max_length=3)),
                ('reason', models.CharField(max_length=30)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(default='Adet', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pages.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
