# Generated by Django 4.1.3 on 2025-10-06 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_image_static'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stok Hareketi', 'verbose_name_plural': 'Stok Hareketleri'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Yapı Kimyasalları', 'Yapı Kimyasalları'), ('Isı Yalıtım', 'Isı Yalıtım'), ('Yapıştırıcı', 'Yapıştırıcı'), ('Dekoratif Sıva', 'Dekoratif Sıva')], max_length=40, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Görsel (Medya)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_static',
            field=models.CharField(blank=True, max_length=200, verbose_name='Statik Görsel Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Asgari Stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pallet_size',
            field=models.PositiveIntegerField(default=64, verbose_name='Palet Büyüklüğü'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='move_type',
            field=models.CharField(choices=[('IN', 'Giriş (+)'), ('OUT', 'Çıkış (-)')], max_length=3, verbose_name='Hareket Tipi'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='pages.product', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(max_length=30, verbose_name='Sebep'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='unit',
            field=models.CharField(default='Adet', max_length=10, verbose_name='Birim'),
        ),
    ]
